### ISSUE TITLE
Does not work or am I wrong???

### ISSUE THREAD

**Issue by jfmennedy** [fhem/fhempy-docker#165]
docker run -d --name fhempy ghcr.io/fhem/ghcr.io/fhem/fhempy-docker_skodaconnect:latest
Unable to find image 'ghcr.io/fhem/ghcr.io/fhem/fhempy-docker_skodaconnect:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/fhem/ghcr.io/fhem/fhempy-docker_skodaconnect/manifests/latest": denied.
See 'docker run --help'.

**Comment by sidey79** [comment]
The correct URI for the image is:

docker pull ghcr.io/fhem/fhempy-docker_skodaconnect:latest

**Comment by jfmennedy** [comment]
thanks :-)

**Comment by jfmennedy** [comment]
Hi, i was able to run the docker i need, but how so i implement them to my  fhem docker ? i do not use docker compose.. Could you please point me the way?

**Comment by jfmennedy** [comment]
But do I need also to define the fhempy_local BindingsIo device and fhempyserver_15733 inside the fhem docker? FHEM docker an fhempy docker running in host mode.. If in bridge or user network my Sonos won't work...

**Comment by sidey79** [comment]
You must follows the documentation for peer setup:

Example: 
- Container ist named fhempy-googleweather
- FHEM and fhempy are on the same Network
- Containername can bei resolved via DNS

`define fhempy_peer_IP BindingsIo fhempy-googleweather:15733 fhempy`


If you are using Host Network, which is normaly not needed, you may have additional steps to be done.
Also note, with Host Network i think you are limited to a single fhempy docker container which limits you to a single module.

**Comment by jfmennedy** [comment]
ok, thank you .. now  i understand better the architecture behind ;-)
