### ISSUE TITLE
Aktualität & Funktionalität des Containers

### ISSUE THREAD

**Issue by Reinschki** [fhem/fhempy-docker#93]
Hallo, 

der Releasestand zeigt an, dass er länger nicht mehr aktualisiert wurde. Daher meine freundliche Frage: Kann der Container noch verwendet werden? Funktionieren damit aktuelle Geräte? Gibt es noch regelmäßige Container Updates?

Ich habe vor mir Tuya Geräte anzuschaffen welche aber letztendlich noch nicht gekauft sind.
Würde das nur mit dem fempy-docker Container machen wollen, da bei mir alles in Docker Containern läuft!

Viele Grüße
Reiner

**Comment by sidey79** [comment]
So wie Fhempy heute entwickelt wurde ist es sehr schwierig das in einem Container zum laufen zu bekommen, da sich einige Module nicht korrekt compiliert werden können.
Auf den ARM Plattformen macht sich das stark bemerkbar, weil es keine Vorkompilierte Pakete gibt.

Ich habe dann für jedes Modul einen eigenen Container gebaut.
Davon habe ich bisher nichts schlechtes gehört, ist aber leider alles sehr instabil im Build Prozess, da es etliche Abhängigkeit gibt.

Für Tuya wäre es dann dieses Image:

https://github.com/fhem/fhempy-docker/pkgs/container/fhempy-docker_tuya

Ich habe den Build Prozess mal wieder gestartet.
Vielleicht hat sich ja irgendwas verbessert.
